name: Create ZIP Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'adno.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig dl_projects'